spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 19871022
    url: jdbc:mysql://localhost/sell?useSSL=false
  jpa:
    show-sql: true
  jackson:
#    空的元素，json不返回给前端
    default-property-inclusion: non_null

server:
    context-path: /sell



#logging:
#  pattern:
##    console: "hblog: %d - %msg%n"
#  level:
#    com.imooc.LoggerTest: debug